name: kycli
summary: The command line interface to the unofficialkyc platform.
description: |
    The command line interface to the unofficialkyc platform.
version: git
base: bare
build-base: core20
grade: devel
confinement: devmode
parts:
    kycli:
        plugin: go
        source: .
        source-type: git
        build-packages: 
            - build-essential
        stage-packages:
            - libc6
            - bash
            - xclip
            - xsel
            - wl-clipboard
        override-build: |
            mkdir -p "${SNAPCRAFT_PART_INSTALL}"
            cd "${SNAPCRAFT_PART_SRC}"
            go build -o "${SNAPCRAFT_PART_INSTALL}"
apps:
    kycli:
        environment: 
            PATH: "$PATH:$SNAP/bin:$SNAP/usr/bin"
        command: kycli
        adapter: none
        plugs:
            - network
            - browser-support
            - wayland
            - x11
